### PR TITLE
Add user-follow-read scope to allow getting followed artists

### PR DESCRIPTION
**Pull request by phts**
I am making modification of spotify volumio plugin and possibility [to access the followed artists](https://developer.spotify.com/documentation/web-api/concepts/scopes#user-follow-read). But there is no required scope for that in your lib.

So this is the missing scope.

Or please describe how to compile this library locally via docker image? What image to use and what commands to run? I will use it with my plugin then. I tried to follow https://www.docker.com/blog/cross-compiling-rust-code-for-multiple-architectures/ but no luck still... :pray:

### CODE REVIEW

**Comment by phts** [comment]
Seems managed to build the binaries. But it required client ID of the app.

May I use existing one or I have to create my own and use it together with my integration?

**Comment by ashthespy** [comment]
Greetings, 
I no longer actively develop Volumio plugin, as my fork of librespot is quite old and outdated. 
Look at Volumio's fork of this repo - [volumio/Vollibrespot](https://github.com/volumio/Vollibrespot/) for the current plugin's backend. 

Also, there a lot of other developments in the years since - look at [librespot-org/librespot](https://github.com/librespot-org/librespot/wiki/Events) or [librespot-org/librespot-java](https://github.com/librespot-org/librespot-java) or [devgianlu/go-librespot](https://github.com/devgianlu/go-librespot) that should use much newer API implementations.

**Comment by phts** [comment]
Thanks, will look at it

**Comment by ashthespy** [comment]
I had time to look at your changes, this isn't such a big one, if you open it will merge it and make a release :-)

**Pull request closed without merging**
